/**:
  ros__parameters:
    dlo/localizationNode/initial_pose_use: true
    dlo/localizationNode/initial_position/x: 1.2755980055608724
    dlo/localizationNode/initial_position/y: 0.7250433821566771
    dlo/localizationNode/initial_position/z: 0.03305981236704579
    dlo/localizationNode/initial_orientation/w: 0.14348069343094266
    dlo/localizationNode/initial_orientation/x: -0.01954237412789702
    dlo/localizationNode/initial_orientation/y: 0.015168041603488391
    dlo/localizationNode/initial_orientation/z: -0.9893438819439556
